version: "3"
services:
  app:
    container_name: app-api
    image: amazoncorretto:17.0.7-alpine3.17
    ports:
      - "80:8080"
    volumes:
      - ./build/libs:/app
    working_dir: /app
    command: ["java", "-jar", "adapter-api.jar"]
    restart: always