springdoc:
  swagger-ui:
    path : '/swagger-ui.html'

token:
  validity:
    lifetime-seconds: 86400
  secret: MjFkcWhkaHF3a2pkMTIzZDEzOWR1MWhkOTFxd2dkdWlhc2RnOTgxMmVnZGJpdXNkYjEyODllaGQxb2lkMTJkMTJlMTJkMXd2dzFjZTI4OWI3NHY5MQ==

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true